### ISSUE TITLE
This extension is not working properly in any way

### ISSUE THREAD

**Issue by lu10539** [ElmouradiAmine/vscode-diagon#1]
When I use the Diagon extension for all generators, it doesn't work properly, it gets an error that the command is failed.
```
  ERR Command failed: node /Users/lulu/.vscode/extensions/elmouradiamine.vscode-diagon-0.0.3/node_modules/@elmouradiamine/diagon/diagon.js Math -- "sqrt(sin(x/2)^2)"
/Users/lulu/.vscode/extensions/elmouradiamine.vscode-diagon-0.0.3/node_modules/@elmouradiamine/diagon/diagon.js:4
"undefined"!==typeof module&&(module.exports=h),process.on("uncaughtException",function(a){if(!(a instanceof ka))throw a;}),process.on("unhandledRejection",function(a){throw a;}),ca=function(a,b){if(noExitRuntime||0<la)throw process.exitCode=a,b;b instanceof ka||z("exiting due to exception: "+b);process.exit(a)},h.inspect=function(){return"[Emscripten Module object]"};else if(da||ea)ea?q=self.location.href:"undefined"!==typeof document&&document.currentScript&&(q=document.currentScript.src),q=0!==
                                                                                                                 ^

TypeError: Failed to parse URL from /Users/lulu/.vscode/extensions/elmouradiamine.vscode-diagon-0.0.3/node_modules/@elmouradiamine/diagon/diagon.wasm
    at Object.fetch (node:internal/deps/undici/undici:12789:11) {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:399:5)
      at URL.onParseError (node:internal/url:565:9)
      at new URL (node:internal/url:645:5)
      at new Request (node:internal/deps/undici/undici:6947:25)
      at fetch2 (node:internal/deps/undici/undici:11930:25)
      at Object.fetch (node:internal/deps/undici/undici:12787:18)
      at fetch (node:internal/process/pre_execution:241:25)
      at /Users/lulu/.vscode/extensions/elmouradiamine.vscode-diagon-0.0.3/node_modules/@elmouradiamine/diagon/diagon.js:67:450
      at /Users/lulu/.vscode/extensions/elmouradiamine.vscode-diagon-0.0.3/node_modules/@elmouradiamine/diagon/diagon.js:68:126
      at Object.<anonymous> (/Users/lulu/.vscode/extensions/elmouradiamine.vscode-diagon-0.0.3/node_modules/@elmouradiamine/diagon/diagon.js:68:139) {
    input: '/Users/lulu/.vscode/extensions/elmouradiamine.vscode-diagon-0.0.3/node_modules/@elmouradiamine/diagon/diagon.wasm',
    code: 'ERR_INVALID_URL'
  }
}

Node.js v19.6.0
: Error: Command failed: node /Users/lulu/.vscode/extensions/elmouradiamine.vscode-diagon-0.0.3/node_modules/@elmouradiamine/diagon/diagon.js Math -- "sqrt(sin(x/2)^2)"
/Users/lulu/.vscode/extensions/elmouradiamine.vscode-diagon-0.0.3/node_modules/@elmouradiamine/diagon/diagon.js:4
"undefined"!==typeof module&&(module.exports=h),process.on("uncaughtException",function(a){if(!(a instanceof ka))throw a;}),process.on("unhandledRejection",function(a){throw a;}),ca=function(a,b){if(noExitRuntime||0<la)throw process.exitCode=a,b;b instanceof ka||z("exiting due to exception: "+b);process.exit(a)},h.inspect=function(){return"[Emscripten Module object]"};else if(da||ea)ea?q=self.location.href:"undefined"!==typeof document&&document.currentScript&&(q=document.currentScript.src),q=0!==
                                                                                                                 ^

TypeError: Failed to parse URL from /Users/lulu/.vscode/extensions/elmouradiamine.vscode-diagon-0.0.3/node_modules/@elmouradiamine/diagon/diagon.wasm
    at Object.fetch (node:internal/deps/undici/undici:12789:11) {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:399:5)
      at URL.onParseError (node:internal/url:565:9)
      at new URL (node:internal/url:645:5)
      at new Request (node:internal/deps/undici/undici:6947:25)
      at fetch2 (node:internal/deps/undici/undici:11930:25)
      at Object.fetch (node:internal/deps/undici/undici:12787:18)
      at fetch (node:internal/process/pre_execution:241:25)
      at /Users/lulu/.vscode/extensions/elmouradiamine.vscode-diagon-0.0.3/node_modules/@elmouradiamine/diagon/diagon.js:67:450
      at /Users/lulu/.vscode/extensions/elmouradiamine.vscode-diagon-0.0.3/node_modules/@elmouradiamine/diagon/diagon.js:68:126
      at Object.<anonymous> (/Users/lulu/.vscode/extensions/elmouradiamine.vscode-diagon-0.0.3/node_modules/@elmouradiamine/diagon/diagon.js:68:139) {
    input: '/Users/lulu/.vscode/extensions/elmouradiamine.vscode-diagon-0.0.3/node_modules/@elmouradiamine/diagon/diagon.wasm',
    code: 'ERR_INVALID_URL'
  }
}

Node.js v19.6.0

    at ChildProcess.exithandler (node:child_process:408:12)
    at ChildProcess.emit (node:events:526:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
```

**Comment by ElmouradiAmine** [comment]
Hello, thank you for pointing that out. I will look into it!

**Comment by zhongjian-ls** [comment]
I'm also having this problem. 
For me, downgrading the system default **Node.js version** from 18 to 16 resolved the issue and allowed the extension to work. 
It would be great if the extension could be updated to support newer Node.js versions. 
I know this is a late response, but I hope it's helpful for anyone else facing the same problem.
